name: iOS Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Force Xcode 14
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app
    - name: Run tests
      run: xcodebuild test -scheme "RandomUsersVIPER" -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest"
